name: daily_news_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  clean_framework: ^3.2.3
  clean_framework_http: ^0.4.1
  clean_framework_router: ^0.5.5
  clean_framework_test: ^0.5.2
  clean_framework_firestore: ^0.5.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  mocktail: ^1.0.1
  pretty_dio_logger: ^1.3.1
  uniform: ^2.0.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  timeago: ^3.6.1
  sqflite: ^2.3.2
  path: ^1.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  network_image_mock: ^2.0.1
  mocktail_image_network: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          # asset: assets/fonts/Lato-Black.ttf
    # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
